### ISSUE TITLE
LogMap error in R-devel with Matrix 1.6-2

### ISSUE THREAD

**Issue by mvfki** [mojaveazure/seurat-object#162]
Hi team,

Greetings from the LIGER team!
Recently, we have been addressing the updates from Seurat 5. We have made some patches and is trying to pass the CRAN check, however it is blocked by the `LogMap()`, only on winbuilder though. I can reproduce the error at my local with the following info:

```
> library(SeuratObject)
Loading required package: sp
‘SeuratObject’ was built with package ‘Matrix’ 1.6.1.1 but the current version is 1.6.2; it is recomended
that you reinstall ‘SeuratObject’ as the ABI for ‘Matrix’ may have changed

Attaching package: ‘SeuratObject’

The following objects are masked from ‘package:base’:

    %||%, intersect

> LogMap(2)
Error in validObject(.Object) : 
  invalid class “LogMap” object: superclass "mMatrix" not defined in the environment of the object's class
> sessionInfo()
R Under development (unstable) (2023-11-06 r85483 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)
Matrix products: default
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SeuratObject_5.0.0 sp_2.1-1          

loaded via a namespace (and not attached):
 [1] digest_0.6.33       progressr_0.14.0    dotCall64_1.1-0     codetools_0.2-19    Matrix_1.6-2       
 [6] lattice_0.22-5      parallel_4.4.0      generics_0.1.3      lifecycle_1.0.4     cli_3.6.1          
[11] parallelly_1.36.0   future_1.33.0       grid_4.4.0          compiler_4.4.0      globals_0.16.2     
[16] rstudioapi_0.15.0   tools_4.4.0         listenv_0.9.0       future.apply_1.11.0 Rcpp_1.0.11        
[21] rlang_1.1.2         spam_2.10-0      
```

It's quite unclear to me why LogMap, which should be just an extension around the base matrix class, can be related to some Matrix classes. However, I found something I can do to get rid of it temporarily which is just `setOldClass("mMatrix")`. And I'm planning to have a `if` condition for Matrix version check to related example code, so that we can have a release asap (rliger is currently archived due to other dependencies). Have you already been aware of such an issue? If so, do you have any suggestion or plan on fixing it?

Best wishes!
LIGER team

**Comment by mojaveazure** [comment]
Hi Yichen,

This is because Matrix recently updated and removed some of their internal class definitions. However, R (not SeuratObject) caches those definitions and so versions of SeuratObject built with an older version of Matrix will still have those internal definitions. However, when loaded using a newer version of Matrix, those definitions don't exist

This explains why win-builder is failing: it's version of SeuratObject was built with Matrix 1.6-1.1, but currently has Matrix 1.6-2; CRAN needs to rebuild binaries for SeuratObject using Matrix 1.6-2 to solve this. If you're trying to submit to CRAN, you should make a note of this to CRAN in your submission comments

**Comment by mvfki** [comment]
Hi Paul,

Thanks for your response! That is close to what I was expecting. I have submitted a version as I planned earlier and it has passed the winbuilder, so I'll just wait for the CRAN team's response for now. But if they give me any comments on that, I guess I will wait for a bit until they get SeuratObject built with Matrix 1.6-2. Thank you again for the clear explanation!
