### ISSUE TITLE
.GetSeuratCompat error while using SCTransform with v2 regularization

### ISSUE THREAD

**Issue by ishwarvh** [mojaveazure/seurat-object#165]
Hello,

I am getting an error about not able find the function .GetSeuratCompat when using SCTransform. 
After spending a whole afternoon searching for the reason and checking if someone else has come across this issue, I think I have stumbled upon a unique error. 

I am running this on a HPC using 16 cores and 128GB of memory, if that matters. 

I have run SCTransform with and without the ```conserve memory = T``` argument,  and in both cases stumbles at the centering data matrix with the following error:

```
Computing corrected UMI count matrix
Place corrected count matrix in counts slot
Centering data matrix
Error in .GetSeuratCompat() : could not find function ".GetSeuratCompat"
Execution halted
```

Here are the package versions I am using:

```
"Package": "Seurat",  "Version": "4.4.0"
"Package": "SeuratObject", "Version": "4.1.4"
```

I would appreciate it if anyone has any input to solve this error!

Thank you,
Ishwar

**Comment by Ztt-0401** [comment]
I had the same problem! Have you solved it now?

**Comment by mushan-guan** [comment]
when i do this, I also had the same problem. Have someone solved it?
sctransform 0.4.0, seurat 4.4.0, seuratobject 4.1.4
`for` (i in 1:length(brain)) {brain[[i]] <- SCTransform(brain[[i]], assay = "Spatial", return.only.var.genes = FALSE, verbose = FALSE)}

**Comment by mojaveazure** [comment]
`.GetSeuratCompat()` was introduced in SeuratObject v5; if you're seeing in with SeuratObject v4 then something is wrong with your SeuratObject installation (eg. you may have multiple installs and R is getting confused). I would recommend restarting your session, uninstalling Seurat/SeuratObject with `remove.packages()` until you get an error saying that the package does not exist, and reinstalling Seurat/SeuratObject

To reinstall Seurat/SeuratObject v5, simply install from CRAN using `install.packages()`

To reinstall Seurat/SeuratObject v4, use
```r
if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
options(repos = c("https://satijalab.r-universe.dev", getOption("repos")))
remotes::install_version("SeuratObject", "4.1.4")
remotes::install_version("Seurat", "4.4.0", upgrade = FALSE) # remotes will try to upgrade SeuratObject to v5, we need to tell it no
```

**Comment by Ztt-0401** [comment]
But seurat v5 sometimes does not meet the analysis needs, is there any way to implement v5 and v4 in parallel?

**Comment by liuliang577** [comment]
After trying the method [mojaveazure] provided, an error still occurred. I don't know why? I am using seurat 4.4.0, seuratobject 4.1.4.  
If someone could help me solve this problem,  I would be very grateful！！

**Comment by liuliang577** [comment]
> 尝试 [mojaveazure] 提供的方法后，仍然发生错误。我不知道为什么？我正在使用 seurat 4.4.0、seuratobject 4.1.4。如果有人能帮我解决这个问题，我将不胜感激！

It's very magical. When I manually uninstalled all the related R packages in the folder, restarted R, and then executed the [mojaveazure]  provided code, I was able to execute SCT normally.
I hope to help those who have relevant questions. Thank [mojaveazure]  very much again

**Comment by jjccco** [comment]
> > 尝试 [mojaveazure] 提供的方法后，仍然发生错误。我不知道为什么？我正在使用 seurat 4.4.0、seuratobject 4.1.4。如果有人能帮我解决这个问题，我将不胜感激！
> 
> It's very magical. When I manually uninstalled all the related R packages in the folder, restarted R, and then executed the [mojaveazure] provided code, I was able to execute SCT normally. I hope to help those who have relevant questions. Thank [mojaveazure] very much again

I just made it work successfully! Please uninstall and then install these packages with a particular version——SeuratObject(4.1.3), sctransform(0.3.5) and Seurat(4.3.0)

**Comment by AmelZulji** [comment]
Just to add: In case you are using `renv` for managing packages, remove the packages first and then use `renv::install()` with `rebuild=T`

**Comment by alicekao1118** [comment]
> `.GetSeuratCompat()` was introduced in SeuratObject v5; if you're seeing in with SeuratObject v4 then something is wrong with your SeuratObject installation (eg. you may have multiple installs and R is getting confused). I would recommend restarting your session, uninstalling Seurat/SeuratObject with `remove.packages()` until you get an error saying that the package does not exist, and reinstalling Seurat/SeuratObject
> 
> To reinstall Seurat/SeuratObject v5, simply install from CRAN using `install.packages()`
> 
> To reinstall Seurat/SeuratObject v4, use
> 
> ```r
> if (!requireNamespace("remotes", quietly = TRUE)) {
>   install.packages("remotes")
> }
> options(repos = c("https://satijalab.r-universe.dev", getOption("repos")))
> remotes::install_version("SeuratObject", "4.1.4")
> remotes::install_version("Seurat", "4.4.0", upgrade = FALSE) # remotes will try to upgrade SeuratObject to v5, we need to tell it no
> ```

This solved my issue!
