### ISSUE TITLE
Fail to merge large objects

### ISSUE THREAD

**Issue by GreenGilad** [mojaveazure/seurat-object#19]
I am trying to merge several large Seurat object iteratively using the following code:

```
  while(length(counts) > 0) {
    obj <- merge(obj, counts[[1]])
    counts[[1]] <- NULL
    pb$tick(tokens = list(ncells=as.character(ncol(obj))))
  }
  
```

where I iterate over `counts` and not use the `merge` feature that accepts a list of objects so to understand at what point it fails. It fails with the following error:

```
Merging groups to single object - 303107 in object 2/9 [====>-----------------]  22% in 16m. ETA  1h
Error in RowMergeMatricesList(mat_list = all.mat, mat_rownames = all.rownames,  :
  vector::reserve
Calls: subset.cell.type ... merge.Assay -> RowMergeSparseMatrices -> RowMergeMatricesList
Execution halted
```

where the first line is printed by the `progress_bar` library. It shows that it crashes once I try to merge the third object into the first+second. All these objects have a similar number of samples and features - so it crashes when trying to create an object of about 450k samples (over I assume about 35-40k features). At the end there are over one million samples to merge between those 9 objects. 

What should I do?

**Comment by GreenGilad** [comment]
At the end I worked around the one problem to find myself in another.  Based on this [SO answer](https://stackoverflow.com/a/52236148/6400526) I merged the different count matrices like this:

```
pb <- progress_bar$new(format=paste0("Merging libraries :current/:total (:cells.prog cells) [:bar] :percent in :elapsed. ETA :eta"),
                       total = length(counts), clear=F, width=100, force = T)

i <- c(); j <- c(); x <- c(); all.colnames <- c();
all.rownames <- sort(unique(unlist(lapply(counts, rownames))))
while(length(counts) > 0) {
  new.row.idx <- match(rownames(counts[[1]]), all.rownames)
  values.idx <- Matrix::which(counts[[1]] > 0, arr.ind = T)
  
  i <- c(i, new.row.idx[values.idx[,1]])
  j <- c(j, max(j, 0)+ unname(values.idx[,2]))
  x <- c(x, counts[[1]]@x)
  all.colnames <- c(all.colnames, colnames(counts[[1]]))
  
  counts[[1]] <- NULL
  pb$tick(tokens=list(cells.prog=paste0(length(all.colnames), "/", nsamples)))
}

obj <- Matrix::sparseMatrix(i=i, j=j, x=x,
                            dimnames = list(all.rownames, all.colnames),
                            dims = c(length(all.rownames), length(all.colnames)))
rm(all.rownames, i, j, x, new.row.idx, values.idx)
obj <- CreateSeuratObject(counts = obj)
```

However this fails when creating the sparse matrix with the error
```
Error in validityMethod(as(object, superClass)) :
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:535
```

Though it means the problem isn't in the Seurat code,  I cannot change the `sparseMatrix` with the `spam64` option because the Seurat code won't know how to handle it. Is there a plan to somehow support such large data? (The overall number of cells is ~760k, number of genes 30~ and number of non-zero values in matrix 4,586,905,017)

**Comment by mojaveazure** [comment]
Hi Gilad, sorry for the delay. Matrix types from the {Matrix} package (eg. `dgCMatrix`) are 32-bit, so there's a limit to the number of non-zero counts a Seurat object can have in a single matrix. We are working on supporting alternate types of matrices in a future version of Seurat, but due to the scale of this project it will be a while before we have a working solution to this problem

**Comment by GreenGilad** [comment]
@mojaveazure Thanks for the reply. If you will need a dataset for testing potential solutions in the future feel free to contact me :)

For future readers - the workaround solution I ended up using is to create two large objects and work with them. I created these objects with some overlap of samples so the two objects will be more similar. Then I was able to clean the data a bit more  (and for my specific case also remove different non-coding features such as AC{numbers}/AF{numbers}/etc) after which I managed to merge the two objects into a single Seurat object. This is not a nice and clean solution but for the time being it worked.

**Comment by shahrozeabbas** [comment]
@GreenGilad I found this post to be relevant to a current problem and I was wondering if you'd be willing to help? 

I am working with 204 samples of 10X Multiome data so there is an RNA and ATAC assay for each object. I have already preprocessed and filtered the data, but am running into issues merging into a single SO. It's an `Cholmod error 'problem too large` error message if that helps at all. 

Anyway, it's 204 `seurat` objects for a total of ~800K measurements each with two assays. My code is simple in that it just takes the list of objects and attempts to merge. 

`object.list <- readRDS('list_of_204_seurat_objects.rds')`
`object <- merge(x=object.list[[1]], y=object.list[-1])`

If I understood your solution correctly, I need to split my on list into two lists of seurat objects with some arbitrary amount of overlap, merge those two lists of objects to create two seurat objects, then merge those two seurat objects into one?

**Comment by Biglinboy** [comment]
@shahrozeabbas Have you solved this problem now? I am also merging 270 seurat objects now, but I also reported an error

**Comment by rubenchazarra** [comment]
@mojaveazure 
I am merging 120 Sparse Matrices from Seurat Objects (approximately 1 million cells in total) with
`Reduce(Seurat::RowMergeSparseMatrices, matrix.list)`
This leads to the following error:
`Error: vector::reserve `

Any clue on how to proceed ?

I am using **Seurat_5.0.2**
