### ISSUE TITLE
how to provide X-Y coordinates for spatial assay using CreateSeuratObject

### ISSUE THREAD

**Issue by linpei26** [mojaveazure/seurat-object#90]
Hello everyone!

when use the function `CreateSeuratObject` given assay = "Spatial",
I am wondering how to add X-Y coordinates to the object?

Thanks in advance!
Best,

Pei

**Comment by alikhuseynov** [comment]
what do you mean exactly, is that spatial data? if yes, what kind?
take a look at some workflows of [image-based spatial transcriptomics ](https://satijalab.org/seurat/articles/spatial_vignette_2.html#overview)

**Comment by mojaveazure** [comment]
Spatial coordinates are stored separate from the assay data. `CreateSeuratObject` initializes a `Seurat` object with assay and cell-level meta data; any additional information (eg. spatial coordinates in the form of an [`FOV`](https://mojaveazure.github.io/seurat-object/reference/FOV-class.html)) must be added separately

```R
obj <- CreateSeuratObject(counts = expr_mat)
# create FOV separately
obj[["coords"]] <- fov
```

**Comment by linpei26** [comment]
Thanks.
